// Constants
OPCODE(CONSTANT)
OPCODE(NIL)
OPCODE(TRUE)
OPCODE(FALSE)

// Comparison
OPCODE(EQUAL)
OPCODE(GREATER)
OPCODE(LESS)

// Binary
OPCODE(ADD)
OPCODE(SUBTRACT)
OPCODE(MULTIPLY)
OPCODE(DIVIDE)
OPCODE(MODULO)
OPCODE(BITWISE_AND)
OPCODE(BITWISE_OR)
OPCODE(BITWISE_XOR)
OPCODE(SHIFT_LEFT)
OPCODE(SHIFT_RIGHT)

// Unary
OPCODE(NOT)
OPCODE(NEGATE)
OPCODE(INCREMENT)
OPCODE(DECREMENT)

// Expressions
OPCODE(POP)
OPCODE(DUP)
OPCODE(GET_LOCAL)
OPCODE(SET_LOCAL)
OPCODE(GET_GLOBAL)
OPCODE(GET_UPVALUE)
OPCODE(SET_UPVALUE)
OPCODE(DEFINE_GLOBAL)
OPCODE(SET_GLOBAL)
OPCODE(GET_PROPERTY)
OPCODE(SET_PROPERTY)
OPCODE(GET_SUPER)
OPCODE(SET_TABLE)
OPCODE(SET_ARRAY)
OPCODE(SLICE)
OPCODE(FORMAT)

// Statements
OPCODE(IMPORT)
OPCODE(DUMP)
OPCODE(JUMP)
OPCODE(JUMP_IF_FALSE)
OPCODE(LOOP)
OPCODE(CALL)
OPCODE(INDEX)
OPCODE(SET_INDEX)
OPCODE(INVOKE)
OPCODE(SUPER_INVOKE)
OPCODE(CLOSURE)
OPCODE(CLOSE_UPVALUE)
OPCODE(RETURN)
OPCODE(REENTER)

// Types
OPCODE(CLASS)
OPCODE(INHERIT)
OPCODE(METHOD)
OPCODE(PROPERTY)
